_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True  True  True  True  True]'
_last_obs:
    value: |-
        [[ 0.5620523   0.59440243 -1.3838396  -2.2434874   0.39584723  2.0979733
           2.276074    0.          0.          0.          0.          0.
           0.          0.        ]
         [ 0.7563867   0.16488107 -1.1852117  -2.460262    0.51212984  1.8271763
           2.0523312   0.          0.          0.          0.          0.
           0.          0.        ]
         [ 1.3247083   0.11958115 -1.2050885  -1.9702644   0.05746078  2.2747388
           1.5849804   0.          0.          0.          0.          0.
           0.          0.        ]
         [ 1.2972482   0.5683843  -0.6969133  -2.325591    0.40664402  2.0679595
           1.7984946   0.          0.          0.          0.          0.
           0.          0.        ]
         [ 1.0464681   0.34369642 -0.71359    -2.2893806  -0.02297115  2.5029008
           2.108347    0.          0.          0.          0.          0.
           0.          0.        ]
         [ 1.3676813   0.264928   -1.2713598  -1.7135258   0.19760595  1.8461955
           1.5112392   0.          0.          0.          0.          0.
           0.          0.        ]
         [ 0.923025    0.48089346 -1.2515373  -2.1386921   0.2491311   2.190712
           1.8164059   0.          0.          0.          0.          0.
           0.          0.        ]
         [ 0.6364506   0.21521308 -0.8882145  -2.4607534   0.4158885   2.3274422
           1.6779052   0.          0.          0.          0.          0.
           0.          0.        ]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x30fcdbcb0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 6e+06
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.24.1
        code_path: code/drake-gym/drake_gym/examples/train_franka_reach_PPO.py
        e:
            sbsk3mj4vgqndn349k20jp0y0bkq50v4:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 48
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "51539607552"
                args:
                    - --net_arch
                    - "256"
                    - "256"
                    - --device
                    - cpu
                    - --checkpoint_freq
                    - "50000"
                    - --wandb
                    - --v_max_scale=0.3
                codePath: drake-gym/drake_gym/examples/train_franka_reach_PPO.py
                codePathLocal: train_franka_reach_PPO.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "233845633024"
                email: xwang0505dazzleyou@gmail.com
                executable: /Users/xiao/miniforge3/envs/robotics/bin/python
                git:
                    commit: c041c5c7eef7f8841ce352018a077d28cadc3cef
                    remote: git@github.com:xiao-wang007/my_rl.git
                host: Mac.lan
                memory:
                    total: "51539607552"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/xiao/0_codes/my_rl/drake-gym/drake_gym/examples/train_franka_reach_PPO.py
                python: CPython 3.12.10
                root: /Users/xiao/0_codes/my_rl/drake-gym/drake_gym/examples
                startedAt: "2026-02-09T15:05:36.748490Z"
                writerId: sbsk3mj4vgqndn349k20jp0y0bkq50v4
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 22
                - 35
            "4": 3.12.10
            "5": 0.24.1
            "12": 0.24.1
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (7,), float32)
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
custom_net:
    value: false
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x16944fa40>
env_name:
    value: panda-reach-v0
env_time_limit:
    value: 10
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
local_log_dir:
    value: logs/panda_reach_ppo
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 8
n_epochs:
    value: 10
n_steps:
    value: 2048
net_arch:
    value:
        - 64
        - 64
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (14,), float32)
observations:
    value: state
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=14, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=14, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=7, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
policy_type:
    value: MlpPolicy
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x1696efe30>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1770649540163275000
target_kl:
    value: None
tensorboard_log:
    value: runs/r2w05jdt
total_timesteps:
    value: 500000
use_sde:
    value: "False"
v_max_scale:
    value: 0.3
verbose:
    value: 1
vf_coef:
    value: 0.5
