_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True  True  True  True  True]'
_last_obs:
    value: |-
        [[ 1.2206538   0.53345454 -1.1862935  -2.0453649   0.2992614   2.5564532
           1.8175678   0.          0.          0.          0.          0.
           0.          0.        ]
         [ 0.48387918 -0.13519892 -1.101259   -2.3268518   0.6462128   2.2599316
           2.3822656   0.          0.          0.          0.          0.
           0.          0.        ]
         [ 1.2445943   0.10436633 -1.1466568  -2.259279    0.43187714  1.7593666
           2.1612105   0.          0.          0.          0.          0.
           0.          0.        ]
         [ 1.1803216  -0.03566793 -1.3722663  -2.5646272   0.05139402  2.2709212
           1.7770355   0.          0.          0.          0.          0.
           0.          0.        ]
         [ 1.3584049   0.7296266  -1.2705879  -2.3121068   0.60109085  1.6966265
           2.0920177   0.          0.          0.          0.          0.
           0.          0.        ]
         [ 0.96098626  0.47108796 -1.1695824  -1.7103858   0.7409602   1.8891098
           2.1440475   0.          0.          0.          0.          0.
           0.          0.        ]
         [ 1.3316832   0.00648989 -0.59835213 -1.966459   -0.17921665  2.2191446
           2.02862     0.          0.          0.          0.          0.
           0.          0.        ]
         [ 0.4217044   0.6352683  -0.5991615  -2.5540557   0.20028222  2.6137643
           2.075272    0.          0.          0.          0.          0.
           0.          0.        ]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x1587e7e30>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 6e+06
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.24.1
        code_path: code/drake-gym/drake_gym/examples/train_franka_reach_PPO.py
        e:
            ceyv20py3shzjqai4ijs8fwe8k5hkdny:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 48
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "51539607552"
                args:
                    - --custom_net
                    - --net_arch
                    - "128"
                    - "128"
                    - --device
                    - cpu
                    - --checkpoint_freq
                    - "50000"
                    - --wandb
                    - --batch_size
                    - "2048"
                codePath: drake-gym/drake_gym/examples/train_franka_reach_PPO.py
                codePathLocal: train_franka_reach_PPO.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "234047356928"
                email: xwang0505dazzleyou@gmail.com
                executable: /Users/xiao/miniforge3/envs/robotics/bin/python
                git:
                    commit: 50a976c556462b0c2fe3a57db52ab5be7dd81100
                    remote: git@github.com:xiao-wang007/my_rl.git
                host: Xiaos-Mac-mini.local
                memory:
                    total: "51539607552"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/xiao/0_codes/my_rl/drake-gym/drake_gym/examples/train_franka_reach_PPO.py
                python: CPython 3.12.10
                root: /Users/xiao/0_codes/my_rl/drake-gym/drake_gym/examples
                startedAt: "2026-02-12T17:06:34.099506Z"
                writerId: ceyv20py3shzjqai4ijs8fwe8k5hkdny
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 22
                - 35
            "4": 3.12.10
            "5": 0.24.1
            "12": 0.24.1
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (7,), float32)
algo:
    value: PPO
batch_size:
    value: 2048
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
custom_net:
    value: true
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x14472e2a0>
env_name:
    value: panda-reach-v0
env_time_limit:
    value: 10
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
local_log_dir:
    value: logs/panda_reach_ppo
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 8
n_epochs:
    value: 10
n_steps:
    value: 2048
net_arch:
    value:
        - 128
        - 128
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (14,), float32)
observations:
    value: state
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=14, out_features=128, bias=True)
              (1): ReLU()
              (2): Linear(in_features=128, out_features=128, bias=True)
              (3): ReLU()
            )
            (value_net): Sequential(
              (0): Linear(in_features=14, out_features=128, bias=True)
              (1): ReLU()
              (2): Linear(in_features=128, out_features=128, bias=True)
              (3): ReLU()
            )
          )
          (action_net): Linear(in_features=128, out_features=7, bias=True)
          (value_net): Linear(in_features=128, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''net_arch'': [128, 128], ''activation_fn'': <class ''torch.nn.modules.activation.ReLU''>}'
policy_type:
    value: MlpPolicy
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x144e51df0>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1770915997496872000
target_kl:
    value: None
tensorboard_log:
    value: runs/p727yph9
total_timesteps:
    value: 500000
use_sde:
    value: "False"
v_max_scale:
    value: 1
verbose:
    value: 1
vf_coef:
    value: 0.5
