_wandb:
    value:
        cli_version: 0.24.1
        code_path: code/drake-gym/drake_gym/examples/train_franka_reach_PPO.py
        e:
            83d01pgw2q75zxstop3a04yr2mban45m:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 48
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "51539607552"
                args:
                    - --net_arch
                    - "256"
                    - "256"
                    - --device
                    - mps
                    - --checkpoint_freq
                    - "50000"
                    - --wandb
                codePath: drake-gym/drake_gym/examples/train_franka_reach_PPO.py
                codePathLocal: train_franka_reach_PPO.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "231829737472"
                email: xwang0505dazzleyou@gmail.com
                executable: /Users/xiao/miniforge3/envs/robotics/bin/python
                git:
                    commit: b77dafd161ccccb38f6a069cc5d48014df157c85
                    remote: git@github.com:xiao-wang007/my_rl.git
                host: Mac.lan
                memory:
                    total: "51539607552"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/xiao/0_codes/my_rl/drake-gym/drake_gym/examples/train_franka_reach_PPO.py
                python: CPython 3.12.10
                root: /Users/xiao/0_codes/my_rl/drake-gym/drake_gym/examples
                startedAt: "2026-02-01T17:55:32.162810Z"
                writerId: 83d01pgw2q75zxstop3a04yr2mban45m
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 22
                - 35
            "4": 3.12.10
            "5": 0.24.1
            "12": 0.24.1
            "13": darwin-arm64
custom_net:
    value: false
env_name:
    value: panda-reach-v0
env_time_limit:
    value: 10
local_log_dir:
    value: logs/panda_reach_ppo
net_arch:
    value:
        - 64
        - 64
observations:
    value: state
policy_type:
    value: MlpPolicy
total_timesteps:
    value: 500000
