_wandb:
    value:
        cli_version: 0.24.1
        code_path: code/drake-gym/drake_gym/examples/train_franka_reach_PPO.py
        e:
            bwcgo1upwmjhk7p05rnha3v5tsjmxwj9:
                args:
                    - --device
                    - cuda
                    - --wandb
                    - --checkpoint_freq
                    - "100000"
                codePath: drake-gym/drake_gym/examples/train_franka_reach_PPO.py
                codePathLocal: train_franka_reach_PPO.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "490577010688"
                        used: "191788371968"
                email: xwang0505dazzleyou@gmail.com
                executable: /home/xiao/pyenvs/robotics/bin/python
                git:
                    commit: 258b8906f0d626f123fca4cd2a18bc02b0087f91
                    remote: git@github.com:xiao-wang007/my_rl.git
                gpu: NVIDIA GeForce GTX 1080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 3584
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce GTX 1080 Ti
                      uuid: GPU-170b4273-400b-edc2-8e93-e7760cf748e5
                host: robotics
                memory:
                    total: "33584930816"
                os: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
                program: /home/xiao/0_codes/my_rl/drake-gym/drake_gym/examples/train_franka_reach_PPO.py
                python: CPython 3.10.12
                root: /home/xiao/0_codes/my_rl/drake-gym/drake_gym/examples
                startedAt: "2026-02-02T23:06:46.300054Z"
                writerId: bwcgo1upwmjhk7p05rnha3v5tsjmxwj9
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 22
                - 35
            "4": 3.10.12
            "5": 0.24.1
            "12": 0.24.1
            "13": linux-x86_64
custom_net:
    value: false
env_name:
    value: panda-reach-v0
env_time_limit:
    value: 10
local_log_dir:
    value: logs/panda_reach_ppo
net_arch:
    value:
        - 64
        - 64
observations:
    value: state
policy_type:
    value: MlpPolicy
total_timesteps:
    value: 500000
