_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True  True  True]'
_last_obs:
    value: |-
        [[-2.15377299 -1.3616891  -0.28596638 -0.501044   -0.51936666  0.36309241
           0.67380332  0.          0.          0.          0.          0.
           0.          0.        ]
         [ 1.572484   -0.83896946  0.42747769 -2.21450291 -1.05041005  0.40398055
           1.4949595   0.          0.          0.          0.          0.
           0.          0.        ]
         [-2.475519   -1.65664563  2.02131285 -0.20980322  2.0851707   1.58360959
           0.05653034  0.          0.          0.          0.          0.
           0.          0.        ]
         [ 0.55878158 -1.42542859 -0.80695774 -0.5695846  -0.67667536  0.32723011
           0.12048994  0.          0.          0.          0.          0.
           0.          0.        ]
         [ 2.17481265  0.84260875  1.28166605 -1.00441379  2.2453754   3.73281681
          -0.92071669  0.          0.          0.          0.          0.
           0.          0.        ]
         [-0.89596055 -0.20832808  2.13832184 -2.7564225   0.56028948  0.89078893
          -1.48097673  0.          0.          0.          0.          0.
           0.          0.        ]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7141c97a6710>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 3e+06
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.24.1
        code_path: code/drake-gym/drake_gym/examples/train_franka_reach_PPO.py
        e:
            i57k7ao1s2biahnm1njzka9i0oc88p5x:
                args:
                    - --device
                    - cpu
                    - --wandb
                    - --checkpoint_freq
                    - "100000"
                codePath: drake-gym/drake_gym/examples/train_franka_reach_PPO.py
                codePathLocal: train_franka_reach_PPO.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "490577010688"
                        used: "191779422208"
                email: xwang0505dazzleyou@gmail.com
                executable: /home/xiao/pyenvs/robotics/bin/python
                git:
                    commit: 258b8906f0d626f123fca4cd2a18bc02b0087f91
                    remote: git@github.com:xiao-wang007/my_rl.git
                gpu: NVIDIA GeForce GTX 1080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 3584
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce GTX 1080 Ti
                      uuid: GPU-170b4273-400b-edc2-8e93-e7760cf748e5
                host: robotics
                memory:
                    total: "33584930816"
                os: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
                program: /home/xiao/0_codes/my_rl/drake-gym/drake_gym/examples/train_franka_reach_PPO.py
                python: CPython 3.10.12
                root: /home/xiao/0_codes/my_rl/drake-gym/drake_gym/examples
                startedAt: "2026-02-02T23:10:14.229692Z"
                writerId: i57k7ao1s2biahnm1njzka9i0oc88p5x
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 22
                - 35
            "4": 3.10.12
            "5": 0.24.1
            "12": 0.24.1
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Box([-2.175 -2.175 -2.175 -2.175 -2.61  -2.61  -2.61 ], [2.175 2.175 2.175 2.175 2.61  2.61  2.61 ], (7,), float32)
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x7141c95a5090>
clip_range_vf:
    value: None
custom_net:
    value: false
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x7141dded5d50>
env_name:
    value: panda-reach-v0
env_time_limit:
    value: 10
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
local_log_dir:
    value: logs/panda_reach_ppo
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x7141ddd49c60>
max_grad_norm:
    value: 0.5
n_envs:
    value: 6
n_epochs:
    value: 10
n_steps:
    value: 2048
net_arch:
    value:
        - 64
        - 64
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: |-
        Box([-2.8973 -1.7628 -2.8973 -3.0718 -2.8973 -0.0175 -2.8973 -2.175  -2.175
         -2.175  -2.175  -2.61   -2.61   -2.61  ], [ 2.8973  1.7628  2.8973 -0.0698  2.8973  3.7525  2.8973  2.175   2.175
          2.175   2.175   2.61    2.61    2.61  ], (14,), float32)
observations:
    value: state
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=14, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=14, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=7, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
policy_type:
    value: MlpPolicy
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7141debb4520>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1770073818950034398
target_kl:
    value: None
tensorboard_log:
    value: runs/d7l2i232
total_timesteps:
    value: 500000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
